[features]
seeds = true
[programs.localnet]
trait_test = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "tEStzwUiictKKqgQvEMiCnguJ4PXVWYy6dHf9nombcJ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --exit"
